spring.application.name=gestion-clinica
server.port=8085
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.aesgsnjoxocqcodzdegw&password=9LODcp1OuAOUHoEs
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT
jwt.secret=4B1846A0B424D1B5FA80ED39AC7D7A04A720612F7C2D90A50F02AEEB61A479C6
jwt.expiration=86400000